### ISSUE TITLE
Make this available via jCenter / maven?

### ISSUE THREAD

**Issue by thokari** [caseyscarborough/groovy-colorizer#1]
Hi, 
just came across this project, and I would suggest that you make this available via public repositories.
Since you are already building with Gradle that should not be an issue.
Basically what you need to do is create a maven artifact using the Gradle Maven Publishing plugin, and then upload the generated pom.xml and the jar file to bintray. Then people can just use Gradle or Maven to get the dependency, and not need download it manually.
For the publish stuff, you can see an example here https://github.com/thokari/gradle-geb-plugin, see build.gradle, however it is an older version of Gradle...
Btw the nice thing about jCenter is that it also uploads your stuff to the maven central repository.

**Comment by caseyscarborough** [comment]
Great idea, thanks! I've added this library to jCenter/Maven. It will be available using the following dependency:

``` xml
<dependency>
    <groupId>com.caseyscarborough.colorizer</groupId>
    <artifactId>groovy-colorizer</artifactId>
    <version>1.0.0</version>
</dependency>
```

**Comment by caseyscarborough** [comment]
Leaving this issue open until it becomes available in jCenter.

**Comment by thokari** [comment]
Apparently that can take some time, thanks for putting it up!

**Comment by thokari** [comment]
I could download it now via jCenter.
